name: Python Test Suite

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/*_python.yml
      - bindings/python/**
      - src/**
      - Cargo.lock
      - Cargo.toml
      - deny.toml
      - .gitmodules
  pull_request:
    paths:
      - .github/workflows/*_python.yml
      - bindings/python/**
      - src/**
      - Cargo.lock
      - Cargo.toml
      - deny.toml
      - .gitmodules

permissions:
  contents: read

jobs:
  test:
    name: Python test
    defaults:
      run:
        working-directory: bindings/python
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.13+freethreaded"
          - "3.14"
          - "3.14+freethreaded"
    runs-on: ${{matrix.os}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: lang-python-${{runner.os}}
      - name: Run Cargo Clippy
        run: cargo clippy
      - name: Run Cargo Fmt
        run: cargo fmt --check
      - name: Run Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@91bf2b620e09e18d6eb78b92e7861937469acedb # v2.0.17
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Install uv - Python Version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: TEST!!
        run: |
          ls -al .
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "bindings/python/.python-version"
          cache: "pip"
      - name: Python - Install dependencies
        run: uv sync
      - name: Lint with Ruff
        run: |
          uv run ruff check --output-format=github .
      - name: Format with Ruff
        run: |
          uv run ruff format --check .
      - name: Build Rust
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          # sccache: "true"
          manylinux: auto
          working-directory: bindings/python
      - name: Run tests
        run: |
          uv run pytest --hypothesis-profile default -n=auto tests/
      - name: Run examples
        run: |
          uv run examples/create_workspace.py
          uv run examples/find_paths.py
          uv run examples/get_path.py
      - name: Run doc tests
        run: |
          uv run sphinx -b=doctest docs/source docs/build
